// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgLdkpEDJSMpGKPiIwHqwHYRU0sGVVPBg',
    appId: '1:127640175838:web:2325a6b1bf3f222a2c2e4f',
    messagingSenderId: '127640175838',
    projectId: 'clickout-cfa95',
    authDomain: 'clickout-cfa95.firebaseapp.com',
    storageBucket: 'clickout-cfa95.firebasestorage.app',
    measurementId: 'G-X6G9Q8RM90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJN5jLOE_c4lHKrrYgDPaK9AhTFuZ5U8U',
    appId: '1:127640175838:android:b64ea8b2980279122c2e4f',
    messagingSenderId: '127640175838',
    projectId: 'clickout-cfa95',
    storageBucket: 'clickout-cfa95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6T6Kt1AwStHvUo_g3gfGVzintiF5ixXE',
    appId: '1:127640175838:ios:7c7d09808e0053022c2e4f',
    messagingSenderId: '127640175838',
    projectId: 'clickout-cfa95',
    storageBucket: 'clickout-cfa95.firebasestorage.app',
    iosBundleId: 'com.clickout.clickoutIdt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6T6Kt1AwStHvUo_g3gfGVzintiF5ixXE',
    appId: '1:127640175838:ios:7c7d09808e0053022c2e4f',
    messagingSenderId: '127640175838',
    projectId: 'clickout-cfa95',
    storageBucket: 'clickout-cfa95.firebasestorage.app',
    iosBundleId: 'com.clickout.clickoutIdt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgLdkpEDJSMpGKPiIwHqwHYRU0sGVVPBg',
    appId: '1:127640175838:web:e5bc9c5083e2cabc2c2e4f',
    messagingSenderId: '127640175838',
    projectId: 'clickout-cfa95',
    authDomain: 'clickout-cfa95.firebaseapp.com',
    storageBucket: 'clickout-cfa95.firebasestorage.app',
    measurementId: 'G-CJLKHNY9CG',
  );
}
